### ISSUE TITLE
the generated  summary in testsummary.txt is nothing

### ISSUE THREAD

**Issue by muguruzawang** [mingzi151/SummPip#1]
When I run the code locally, I find the testSummary.txt is empty.  I debug the code  and find the code in function "get_compressed_sen" of summrizer.py:

compresser = takahe.word_graph(sentence_list = sentences, nb_words = self.nb_words, lang = 'en', punct_tag = "." )
candidates = compresser.get_compression(3)

candidates return  NULL

could you please help me with the situation, THX. @mingzi151

**Comment by mingzi151** [comment]
Hi,

I presume you are testing SummPip on your own data. In that case, one cause for none candidates could be that your input documents are too short, and after the second stage of SummPip, i.e., graph construction, some clusters have no sentences. Can you please check to see if this what happened? Leave me a message if there are still issues.

Cheers.
